language: python

python:
   - "3.5"

before-install:
    - pip install --upgrade pip

install:
    - pip install autopep8
    - pip install coverage
    - pip install numpy
    - pip install pylint
    - pip install pydoc

before_script:
    - uname -a
    - printenv | sort

script:
    - date
    - ls -al
    - make test